In [226]:
#reading file 
import pandas as pd
with open('EV_sales.csv') as E:
    ev=pd.read_csv(E)
ev

,RecordID,Year,State,Manufacturer,VehicleType,EVSales,BatteryCapacity
0,1,2021,Andhra Pradesh,BYD,Electric Scooter,2106,30
1,2,2022,Gujarat,Tata,Electric Bike,4567,13
2,3,2025,Tamil Nadu,Tata,Electric Car,867,29
3,4,2022,Maharashtra,Mahindra,Electric Car,4697,27
4,5,2025,Tamil Nadu,Ola,Electric Scooter,4927,37
...,...,...,...,...,...,...,...
145,146,2021,Andhra Pradesh,MG,Electric Scooter,706,75
146,147,2021,Telangana,Ola,Electric Bike,2589,12
147,148,2022,Andhra Pradesh,Mahindra,Electric Scooter,4983,30
148,149,2025,Tamil Nadu,MG,Electric Scooter,2535,56
149,150,2023,Maharashtra,Mahindra,Electric Car,912,28

In [227]:
#displaying first 5 recording
ev.head(5)

,RecordID,Year,State,Manufacturer,VehicleType,EVSales,BatteryCapacity
0,1,2021,Andhra Pradesh,BYD,Electric Scooter,2106,30
1,2,2022,Gujarat,Tata,Electric Bike,4567,13
2,3,2025,Tamil Nadu,Tata,Electric Car,867,29
3,4,2022,Maharashtra,Mahindra,Electric Car,4697,27
4,5,2025,Tamil Nadu,Ola,Electric Scooter,4927,37

In [228]:
#displaying first 5 recording
ev.tail(5)

,RecordID,Year,State,Manufacturer,VehicleType,EVSales,BatteryCapacity
145,146,2021,Andhra Pradesh,MG,Electric Scooter,706,75
146,147,2021,Telangana,Ola,Electric Bike,2589,12
147,148,2022,Andhra Pradesh,Mahindra,Electric Scooter,4983,30
148,149,2025,Tamil Nadu,MG,Electric Scooter,2535,56
149,150,2023,Maharashtra,Mahindra,Electric Car,912,28

### Basic analysis
1. What is the shape of the dataset?
2. What are the column names?
3.  What are the data types of each column?
4.  What is the summary statistics of the dataset?
5.  How many unique manufacturers are present?

In [229]:
#1. What is the shape of the dataset?
print(f"Shape of the Dataset is{ev.shape}")

Shape of the Dataset is(150, 7)

In [230]:
#2. What are the column names?
print(f"The column names of the Dataset are")
ev.columns

The column names of the Dataset are

Index(['RecordID', 'Year', 'State', 'Manufacturer', 'VehicleType', 'EVSales',
       'BatteryCapacity'],
      dtype='object')

In [231]:
#3.  What are the data types of each column?
print(f"Data type of each column")
ev.dtypes

Data type of each column

RecordID            int64
Year                int64
State              object
Manufacturer       object
VehicleType        object
EVSales             int64
BatteryCapacity     int64
dtype: object

In [232]:
#4.  What is the summary statistics of the dataset?
ev.describe()

         RecordID         Year      EVSales  BatteryCapacity
count  150.000000   150.000000   150.000000       150.000000
mean    75.500000  2023.026667  2635.513333        37.493333
std     43.445368     1.394845  1418.464619        20.730533
min      1.000000  2021.000000   145.000000         2.000000
25%     38.250000  2022.000000  1348.750000        22.000000
50%     75.500000  2023.000000  2600.000000        35.000000
75%    112.750000  2024.000000  3967.000000        56.000000
max    150.000000  2025.000000  4988.000000        75.000000

In [233]:
#5.  How many unique manufacturers are present?
ev["Manufacturer"].nunique()

6

In [234]:
# printing unique manufacturers
for i in ev["Manufacturer"].unique():
    print(i)

BYD
Tata
Mahindra
Ola
Ather
MG