In [1]:
#reading file 
import pandas as pd
with open('EV_sales.csv') as E:
    ev=pd.read_csv(E)
ev

,RecordID,Year,State,Manufacturer,VehicleType,EVSales,BatteryCapacity
0,1,2021,Andhra Pradesh,BYD,Electric Scooter,2106,30
1,2,2022,Gujarat,Tata,Electric Bike,4567,13
2,3,2025,Tamil Nadu,Tata,Electric Car,867,29
3,4,2022,Maharashtra,Mahindra,Electric Car,4697,27
4,5,2025,Tamil Nadu,Ola,Electric Scooter,4927,37
...,...,...,...,...,...,...,...
145,146,2021,Andhra Pradesh,MG,Electric Scooter,706,75
146,147,2021,Telangana,Ola,Electric Bike,2589,12
147,148,2022,Andhra Pradesh,Mahindra,Electric Scooter,4983,30
148,149,2025,Tamil Nadu,MG,Electric Scooter,2535,56
149,150,2023,Maharashtra,Mahindra,Electric Car,912,28

###  Data cleaning 
 6. Are there any missing values in the dataset?
 7. Are there any duplicate records in the dataset?
 8. Are there any inconsistent manufacturer names?
 9. Are there any invalid model years?
 10. Are there any missing or unknown vehicle types
 11. . Are there any inconsistent state, city, or county names?

In [4]:
# 6. Are there any missing values in the dataset?
if any(ev.isnull().sum()):
    print("Yes")
else :
    print("No")

No

In [5]:
ev.isnull().sum()

RecordID           0
Year               0
State              0
Manufacturer       0
VehicleType        0
EVSales            0
BatteryCapacity    0
dtype: int64

In [6]:
# 7. Are there any duplicate records in the dataset?
if ev.duplicated().any():
    print("Yes")
else:
    print("NO")

NO

In [7]:
ev.duplicated().sum()

np.int64(0)

In [8]:
#8.Are there any inconsistent manufacturer names?
ev["Manufacturer"].unique()

array(['BYD', 'Tata', 'Mahindra', 'Ola', 'Ather', 'MG'], dtype=object)

In [9]:
if all(ev["Manufacturer"].unique()):
    print("Yes")
else:
    print("No")

Yes

In [10]:
#9. Are there any invalid model years?
ev["Year"].describe()

count     150.000000
mean     2023.026667
std         1.394845
min      2021.000000
25%      2022.000000
50%      2023.000000
75%      2024.000000
max      2025.000000
Name: Year, dtype: float64

In [11]:
#10. Are there any missing or unknown vehicle types?
ev["VehicleType"].value_counts()

VehicleType
Electric Scooter    51
Electric Car        51
Electric Bike       48
Name: count, dtype: int64

In [12]:
#11. Are there any inconsistent state, city, or county names?
if all(ev["State"].unique()):
    print("Yes")
else:
    print("No")

Yes

In [13]:
for i in ev["State"].unique():
    print(i)

Andhra Pradesh
Gujarat
Tamil Nadu
Maharashtra
Telangana
Karnataka

### Data Filtering
12. Which records belong to Andhra Pradesh?
13. Which vehicles have EV sales greater than 3000?
14. Which records correspond to Electric Cars?
15. Which Tata vehicles were sold in 2024?
16. Which vehicles have battery capacity greater than 50 kWh?

In [14]:
#12. Which records belong to Andhra Pradesh?
ev[ev["State"]=="Andhra Pradesh"]

,RecordID,Year,State,Manufacturer,VehicleType,EVSales,BatteryCapacity
0,1,2021,Andhra Pradesh,BYD,Electric Scooter,2106,30
10,11,2021,Andhra Pradesh,BYD,Electric Car,2470,12
11,12,2022,Andhra Pradesh,MG,Electric Scooter,3814,48
15,16,2023,Andhra Pradesh,Ola,Electric Car,2684,53
16,17,2023,Andhra Pradesh,Ola,Electric Bike,2677,29
23,24,2025,Andhra Pradesh,BYD,Electric Bike,1038,70
28,29,2025,Andhra Pradesh,Mahindra,Electric Scooter,4102,4
30,31,2025,Andhra Pradesh,Tata,Electric Bike,4081,10
35,36,2022,Andhra Pradesh,Ather,Electric Car,4919,72
37,38,2022,Andhra Pradesh,Tata,Electric Scooter,680,67
45,46,2025,Andhra Pradesh,Tata,Electric Bike,4528,3
54,55,2025,Andhra Pradesh,MG,Electric Bike,4881,74
57,58,2023,Andhra Pradesh,Tata,Electric Scooter,4712,14
59,60,2023,Andhra Pradesh,Ola,Electric Scooter,2434,22
62,63,2021,Andhra Pradesh,BYD,Electric Bike,1373,36
67,68,2025,Andhra Pradesh,Tata,Electric Car,1321,71
69,70,2022,Andhra Pradesh,Ather,Electric Scooter,426,47
78,79,2021,Andhra Pradesh,Ather,Electric Car,4856,35
79,80,2021,Andhra Pradesh,Mahindra,Electric Scooter,2931,42
83,84,2024,Andhra Pradesh,BYD,Electric Scooter,2671,17
92,93,2022,Andhra Pradesh,Tata,Electric Car,3992,11
105,106,2024,Andhra Pradesh,Ola,Electric Scooter,3290,4
115,116,2025,Andhra Pradesh,Ather,Electric Car,662,7
122,123,2025,Andhra Pradesh,Mahindra,Electric Car,2944,70
131,132,2025,Andhra Pradesh,Mahindra,Electric Car,801,32
133,134,2024,Andhra Pradesh,Tata,Electric Scooter,1915,53
137,138,2022,Andhra Pradesh,BYD,Electric Car,2684,17
141,142,2023,Andhra Pradesh,BYD,Electric Bike,1136,37
142,143,2021,Andhra Pradesh,Mahindra,Electric Scooter,1134,64
143,144,2021,Andhra Pradesh,Mahindra,Electric Scooter,3945,63
145,146,2021,Andhra Pradesh,MG,Electric Scooter,706,75
147,148,2022,Andhra Pradesh,Mahindra,Electric Scooter,4983,30

In [15]:
#13. Which vehicles have EV sales greater than 3000?
ev[ev["EVSales"]>3000]

,RecordID,Year,State,Manufacturer,VehicleType,EVSales,BatteryCapacity
1,2,2022,Gujarat,Tata,Electric Bike,4567,13
3,4,2022,Maharashtra,Mahindra,Electric Car,4697,27
4,5,2025,Tamil Nadu,Ola,Electric Scooter,4927,37
9,10,2023,Gujarat,Mahindra,Electric Scooter,4829,26
11,12,2022,Andhra Pradesh,MG,Electric Scooter,3814,48
14,15,2024,Tamil Nadu,Ather,Electric Bike,4662,30
18,19,2022,Telangana,BYD,Electric Bike,4515,35
19,20,2025,Tamil Nadu,Mahindra,Electric Scooter,3065,30
21,22,2022,Gujarat,Ola,Electric Bike,3558,10
22,23,2024,Tamil Nadu,Mahindra,Electric Scooter,4434,34
28,29,2025,Andhra Pradesh,Mahindra,Electric Scooter,4102,4
30,31,2025,Andhra Pradesh,Tata,Electric Bike,4081,10
31,32,2025,Telangana,Ola,Electric Bike,3993,72
32,33,2022,Karnataka,Mahindra,Electric Bike,3566,29
35,36,2022,Andhra Pradesh,Ather,Electric Car,4919,72
39,40,2022,Gujarat,Mahindra,Electric Bike,3972,33
45,46,2025,Andhra Pradesh,Tata,Electric Bike,4528,3
46,47,2021,Telangana,Ola,Electric Scooter,4078,63
47,48,2022,Tamil Nadu,Tata,Electric Car,3204,2
48,49,2024,Karnataka,MG,Electric Scooter,3565,73
51,52,2021,Maharashtra,MG,Electric Bike,4450,22
54,55,2025,Andhra Pradesh,MG,Electric Bike,4881,74
57,58,2023,Andhra Pradesh,Tata,Electric Scooter,4712,14
60,61,2024,Maharashtra,BYD,Electric Scooter,4433,3
66,67,2023,Telangana,BYD,Electric Scooter,4619,56
77,78,2023,Gujarat,Mahindra,Electric Scooter,4492,44
78,79,2021,Andhra Pradesh,Ather,Electric Car,4856,35
80,81,2024,Maharashtra,Mahindra,Electric Car,3255,75
81,82,2022,Karnataka,Tata,Electric Bike,3672,2
84,85,2023,Maharashtra,Ather,Electric Bike,3445,43
89,90,2024,Tamil Nadu,BYD,Electric Car,4287,62
90,91,2022,Gujarat,Tata,Electric Scooter,4322,44
92,93,2022,Andhra Pradesh,Tata,Electric Car,3992,11
95,96,2024,Telangana,Ola,Electric Bike,4343,61
96,97,2021,Maharashtra,Ola,Electric Car,3839,19
97,98,2024,Gujarat,Mahindra,Electric Bike,4977,42
98,99,2024,Maharashtra,BYD,Electric Bike,3595,72
99,100,2024,Telangana,BYD,Electric Scooter,3786,35
100,101,2022,Gujarat,Ather,Electric Bike,4069,32
104,105,2021,Tamil Nadu,MG,Electric Scooter,4545,61
105,106,2024,Andhra Pradesh,Ola,Electric Scooter,3290,4
107,108,2024,Tamil Nadu,Mahindra,Electric Bike,4573,30
108,109,2024,Telangana,Ather,Electric Scooter,4078,5
109,110,2024,Karnataka,BYD,Electric Bike,3412,23
114,115,2023,Tamil Nadu,Ather,Electric Car,3952,4
117,118,2022,Tamil Nadu,BYD,Electric Car,4720,29
123,124,2024,Gujarat,Ather,Electric Car,4244,45
124,125,2021,Tamil Nadu,MG,Electric Car,3651,48
126,127,2023,Maharashtra,Mahindra,Electric Scooter,3908,57
128,129,2024,Telangana,MG,Electric Bike,3204,45
129,130,2021,Tamil Nadu,Ather,Electric Car,4094,29
130,131,2023,Karnataka,Ather,Electric Scooter,4983,37
132,133,2024,Tamil Nadu,Mahindra,Electric Car,4000,64
134,135,2022,Karnataka,BYD,Electric Bike,3123,62
135,136,2025,Maharashtra,Ather,Electric Scooter,4608,44
139,140,2023,Gujarat,Mahindra,Electric Bike,4988,38
140,141,2021,Telangana,Ather,Electric Car,3056,24
143,144,2021,Andhra Pradesh,Mahindra,Electric Scooter,3945,63
147,148,2022,Andhra Pradesh,Mahindra,Electric Scooter,4983,30

In [16]:
#14. Which records correspond to Electric Cars?
ev[ev["VehicleType"]=="Electric Car"]

,RecordID,Year,State,Manufacturer,VehicleType,EVSales,BatteryCapacity
2,3,2025,Tamil Nadu,Tata,Electric Car,867,29
3,4,2022,Maharashtra,Mahindra,Electric Car,4697,27
6,7,2022,Telangana,Ather,Electric Car,859,50
10,11,2021,Andhra Pradesh,BYD,Electric Car,2470,12
12,13,2022,Karnataka,Ather,Electric Car,2287,11
15,16,2023,Andhra Pradesh,Ola,Electric Car,2684,53
20,21,2022,Maharashtra,MG,Electric Car,485,16
24,25,2023,Gujarat,Ather,Electric Car,2504,57
29,30,2021,Karnataka,Ather,Electric Car,574,32
33,34,2025,Gujarat,BYD,Electric Car,2653,53
35,36,2022,Andhra Pradesh,Ather,Electric Car,4919,72
36,37,2022,Maharashtra,Ola,Electric Car,681,9
40,41,2024,Tamil Nadu,Ola,Electric Car,894,57
44,45,2022,Karnataka,MG,Electric Car,717,58
47,48,2022,Tamil Nadu,Tata,Electric Car,3204,2
50,51,2025,Gujarat,Mahindra,Electric Car,2669,9
52,53,2021,Maharashtra,Tata,Electric Car,661,10
55,56,2025,Karnataka,Ather,Electric Car,2673,32
61,62,2025,Karnataka,BYD,Electric Car,1200,35
65,66,2024,Karnataka,Tata,Electric Car,2832,18
67,68,2025,Andhra Pradesh,Tata,Electric Car,1321,71
72,73,2022,Telangana,MG,Electric Car,1569,44
73,74,2024,Gujarat,BYD,Electric Car,2285,22
75,76,2024,Karnataka,Ather,Electric Car,1926,5
78,79,2021,Andhra Pradesh,Ather,Electric Car,4856,35
80,81,2024,Maharashtra,Mahindra,Electric Car,3255,75
87,88,2023,Tamil Nadu,Mahindra,Electric Car,2589,38
89,90,2024,Tamil Nadu,BYD,Electric Car,4287,62
92,93,2022,Andhra Pradesh,Tata,Electric Car,3992,11
94,95,2024,Tamil Nadu,Ola,Electric Car,145,15
96,97,2021,Maharashtra,Ola,Electric Car,3839,19
106,107,2025,Tamil Nadu,MG,Electric Car,2981,40
111,112,2025,Maharashtra,BYD,Electric Car,787,56
112,113,2022,Tamil Nadu,Ola,Electric Car,2231,50
114,115,2023,Tamil Nadu,Ather,Electric Car,3952,4
115,116,2025,Andhra Pradesh,Ather,Electric Car,662,7
116,117,2021,Telangana,Ola,Electric Car,1348,32
117,118,2022,Tamil Nadu,BYD,Electric Car,4720,29
121,122,2025,Gujarat,BYD,Electric Car,934,40
122,123,2025,Andhra Pradesh,Mahindra,Electric Car,2944,70
123,124,2024,Gujarat,Ather,Electric Car,4244,45
124,125,2021,Tamil Nadu,MG,Electric Car,3651,48
127,128,2025,Karnataka,Ather,Electric Car,809,37
129,130,2021,Tamil Nadu,Ather,Electric Car,4094,29
131,132,2025,Andhra Pradesh,Mahindra,Electric Car,801,32
132,133,2024,Tamil Nadu,Mahindra,Electric Car,4000,64
137,138,2022,Andhra Pradesh,BYD,Electric Car,2684,17
138,139,2025,Gujarat,Ola,Electric Car,1872,63
140,141,2021,Telangana,Ather,Electric Car,3056,24
144,145,2024,Karnataka,Ola,Electric Car,2168,63
149,150,2023,Maharashtra,Mahindra,Electric Car,912,28

In [17]:
#15. Which Tata vehicles were sold in 2024?
ev[(ev["Manufacturer"]=="Tata") & (ev["Year"]==2024)]

,RecordID,Year,State,Manufacturer,VehicleType,EVSales,BatteryCapacity
8,9,2024,Maharashtra,Tata,Electric Scooter,745,72
65,66,2024,Karnataka,Tata,Electric Car,2832,18
133,134,2024,Andhra Pradesh,Tata,Electric Scooter,1915,53

In [18]:
#16. Which vehicles have battery capacity greater than 50 kWh?
ev[ev["BatteryCapacity"]>50]

,RecordID,Year,State,Manufacturer,VehicleType,EVSales,BatteryCapacity
8,9,2024,Maharashtra,Tata,Electric Scooter,745,72
15,16,2023,Andhra Pradesh,Ola,Electric Car,2684,53
23,24,2025,Andhra Pradesh,BYD,Electric Bike,1038,70
24,25,2023,Gujarat,Ather,Electric Car,2504,57
25,26,2022,Tamil Nadu,Tata,Electric Bike,2257,66
26,27,2022,Maharashtra,Tata,Electric Bike,2544,66
27,28,2025,Telangana,Ola,Electric Scooter,1423,71
31,32,2025,Telangana,Ola,Electric Bike,3993,72
33,34,2025,Gujarat,BYD,Electric Car,2653,53
35,36,2022,Andhra Pradesh,Ather,Electric Car,4919,72
37,38,2022,Andhra Pradesh,Tata,Electric Scooter,680,67
38,39,2022,Karnataka,BYD,Electric Scooter,1855,71
40,41,2024,Tamil Nadu,Ola,Electric Car,894,57
43,44,2022,Telangana,Mahindra,Electric Scooter,1248,56
44,45,2022,Karnataka,MG,Electric Car,717,58
46,47,2021,Telangana,Ola,Electric Scooter,4078,63
48,49,2024,Karnataka,MG,Electric Scooter,3565,73
54,55,2025,Andhra Pradesh,MG,Electric Bike,4881,74
56,57,2023,Tamil Nadu,Ola,Electric Bike,2557,60
66,67,2023,Telangana,BYD,Electric Scooter,4619,56
67,68,2025,Andhra Pradesh,Tata,Electric Car,1321,71
68,69,2021,Karnataka,Mahindra,Electric Bike,1313,57
80,81,2024,Maharashtra,Mahindra,Electric Car,3255,75
86,87,2024,Gujarat,MG,Electric Bike,1525,74
88,89,2022,Tamil Nadu,Mahindra,Electric Bike,2739,61
89,90,2024,Tamil Nadu,BYD,Electric Car,4287,62
93,94,2024,Tamil Nadu,BYD,Electric Bike,1692,51
95,96,2024,Telangana,Ola,Electric Bike,4343,61
98,99,2024,Maharashtra,BYD,Electric Bike,3595,72
104,105,2021,Tamil Nadu,MG,Electric Scooter,4545,61
110,111,2024,Telangana,Mahindra,Electric Bike,320,52
111,112,2025,Maharashtra,BYD,Electric Car,787,56
122,123,2025,Andhra Pradesh,Mahindra,Electric Car,2944,70
125,126,2024,Gujarat,Ola,Electric Scooter,1542,68
126,127,2023,Maharashtra,Mahindra,Electric Scooter,3908,57
132,133,2024,Tamil Nadu,Mahindra,Electric Car,4000,64
133,134,2024,Andhra Pradesh,Tata,Electric Scooter,1915,53
134,135,2022,Karnataka,BYD,Electric Bike,3123,62
138,139,2025,Gujarat,Ola,Electric Car,1872,63
142,143,2021,Andhra Pradesh,Mahindra,Electric Scooter,1134,64
143,144,2021,Andhra Pradesh,Mahindra,Electric Scooter,3945,63
144,145,2024,Karnataka,Ola,Electric Car,2168,63
145,146,2021,Andhra Pradesh,MG,Electric Scooter,706,75
148,149,2025,Tamil Nadu,MG,Electric Scooter,2535,56